name: twipe_flutter_core
description: Twipe Flutter Core
version: 0.11.9
homepage: https://github.com/FarukErtuerk
repository: https://github.com/FarukErtuerk/twipe_flutter_core

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
#  assets:
#   - .env.example
#   - resources/styles/themes.json
#   - resources/json/